/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_ndklibtest3_MainActivity */

#ifndef _Included_com_example_ndklibtest3_MainActivity
#define _Included_com_example_ndklibtest3_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ndklibtest3_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_ndklibtest3_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_ndklibtest3_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT float JNICALL Java_com_example_ndklibtest3_MainActivity_AnalogGageIndicatorVal
  (JNIEnv *, jobject, jlong , jint, jint, jint, jfloat, jlong);

JNIEXPORT float JNICALL Java_com_example_ndklibtest3_MainActivity_FindCircle
        //(JNIEnv *, jobject, jlong, jint , jint , jint );
    (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
